# Problem 1
Import the NumPy library under the alias `np`.

In [1]:
import numpy as np

# Problem 2
Create a NumPy array called `my_array` that contains the following elements: `1`, `3`, and `5`.

In [2]:
my_array = np.array([1, 3, 5])

# Problem 3
Create a two-dimensional NumPy array with 9 elements. The array should be called `my_matrix` and should have 3 columns and three rows. The matrix can contain whatever values you'd like. 

In [3]:
my_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# Problem 4
Use NumPy's `arange` method to generate the following output:

`array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])`

In [4]:
np.arange(0, 21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# Problem 5
Use NumPy's `arange` method to generate the following output:

`array([ 1,  4,  7, 10, 13])`

Hint: You will need to use `arange`'s third argument.

In [5]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

# Problem 6
Generate a NumPy array that contains 20 zeros.

In [6]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# Problem 7
Generate a NumPy array that contains 50 ones.

In [7]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Problem 8
Using NumPy, divide the space between 0 and 100 into 1000 even intervals.

In [8]:
np.linspace(0,100,1000)

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

# Problem 9
Create a 10x10 identity matrix using NumPy.

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Problem 10
Returns a random sample of numbers with 10 values where each value is between 0 and 1.

In [10]:
np.random.rand(10)

array([0.19170402, 0.55645186, 0.65700129, 0.1648909 , 0.58771596,
       0.78439065, 0.06312085, 0.46611294, 0.57032727, 0.31190655])

# Problem 11
Returns a random sample of numbers with 10 values where each value is between 0 and 10.

Hint: Use the `random.rand` method combined with a multiplication operation.

In [11]:
np.random.rand(10)*10

array([1.80533202, 8.3994994 , 1.57603441, 9.13256339, 9.97815142,
       4.7302086 , 3.80373864, 4.678893  , 0.96672324, 8.55569928])

# Problem 12
Generate a random sample of 15 numbers from a normal distribution.

In [12]:
np.random.randn(15)

array([-0.34623648,  0.31064557, -0.4459493 , -1.40253534,  0.49850674,
       -0.29975628,  1.21338415, -0.484629  , -0.4221513 ,  1.01339043,
        1.00563727,  0.73421987, -0.62300471,  0.84863864,  0.32504362])

# Problem 13
Generate a random sample of 7 integers that range between 5 and 10.

In [13]:
np.random.randint(5, 10, 7)

array([6, 5, 7, 7, 5, 8, 8])

# Problem 14
Reshape the following one-dimensional NumPy array into a two-dimensional Numpy array with 3 rows and 3 columns.

In [14]:
arr = np.array([0,1,2,3,4,5,6,7,8])
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Problem 15
Print the minimum and maximum values of the following NumPy array.

In [15]:
arr = np.array([0,1,2,3,4,5,6,7,8])

In [16]:
#Print the minimum value here.
arr.min()

0

In [17]:
#Print the maximum value here.
arr.max()

8

# Problem 16
For the following NumPy array, print the index of the minimum and maximum values.

In [18]:
my_array = np.array([6, 7, 0, 2])

In [19]:
#Print the minimum value's index here.
my_array.argmin()

2

In [20]:
#Print the maximum value's index here.
my_array.argmax()

1